services:
  db:
    image: postgres:15
    container_name: postgres_si1
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_USER: alumnodb
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: si1
    ports:
      - "9999:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      #- ./populate.sql:/docker-entrypoint-initdb.d/2_populate.sql
      - ./db_data:/var/lib/postgresql/data

volumes:
  db_data:

