version: "3.9"

services:
  user_service:
    build:
      context: ./user
      dockerfile: Dockerfile
    container_name: user_service
    ports:
      - "5050:5050"   

  file_service:
    build:
      context: ./file
      dockerfile: Dockerfile
    container_name: file_service
    ports:
      - "5051:5051"


    