ALTER TABLE movie
	ADD COLUMN stock INT NOT NULL DEFAULT 0,
	ADD COLUMN rating DECIMAL(2,1) DEFAULT 0.0,
	ADD CONSTRAINT movie_rating_check CHECK (rating >= 0.0 AND rating <= 5);

ALTER TABLE "user"
	ADD COLUMN nationality VARCHAR(100),
	ADD COLUMN discount INT NOT NULL DEFAULT 0;

ALTER TABLE carts
	ADD COLUMN price DECIMAL(10,2) NOT NULL DEFAULT 0;

